In [1]:
import numpy as np
import torch
import torch.nn as nn

torch.__version__

'1.5.1'

##### torch.rand() - samples from a uniform distribution on the interval [0, 1)
##### torch.randn() - samples from a normal distribution with mean=0 and sigma=1
##### torch.randint(low, high, size) - samples integers randomly from low to high-1

In [2]:
x = torch.randn(4, 2)
y = torch.randn(4, 2)

print('X:', x, '\nY:', y)

X: tensor([[ 0.6883,  0.3446],
        [-0.7575,  0.9242],
        [-1.4080, -0.7028],
        [ 0.8315,  1.9197]]) 
Y: tensor([[-1.0840,  0.2673],
        [ 0.4967, -0.8676],
        [-1.2101,  0.4709],
        [-1.0370, -1.3903]])


### L1 Loss

In [3]:
# torch implementation
print('Loss per Element:\n', nn.L1Loss(reduction='none')(x, y))
print('Mean Loss:', nn.L1Loss()(x, y))

Loss per Element:
 tensor([[1.7723, 0.0773],
        [1.2542, 1.7918],
        [0.1979, 1.1737],
        [1.8685, 3.3100]])
Mean Loss: tensor(1.4307)


In [4]:
# numpy implementation
L1 = abs(x.numpy() - y.numpy())
print('Loss per Element:\n', L1)
print('Mean Loss:', L1.mean())

Loss per Element:
 [[1.772349   0.07731536]
 [1.2541883  1.7918162 ]
 [0.19786525 1.1737468 ]
 [1.8685338  3.3100104 ]]
Mean Loss: 1.4307282


### L2 / MSE Loss

In [5]:
# torch implementation
print('Loss per Element:\n', nn.MSELoss(reduction='none')(x, y))
print('Mean Loss:', nn.MSELoss()(x, y))

Loss per Element:
 tensor([[3.1412e+00, 5.9777e-03],
        [1.5730e+00, 3.2106e+00],
        [3.9151e-02, 1.3777e+00],
        [3.4914e+00, 1.0956e+01]])
Mean Loss: tensor(2.9744)


In [6]:
# numpy implementation
L2 = (x.numpy() - y.numpy())**2
print('Loss per Element:\n', L2)
print('Mean Loss:', L2.mean())

Loss per Element:
 [[3.1412210e+00 5.9776651e-03]
 [1.5729883e+00 3.2106054e+00]
 [3.9150655e-02 1.3776816e+00]
 [3.4914188e+00 1.0956169e+01]]
Mean Loss: 2.9744015


### Smooth L1 Loss

In [7]:
# torch implementation
print('Loss per Element:\n', nn.SmoothL1Loss(reduction='none')(x, y))
print('Mean Loss:', nn.SmoothL1Loss()(x, y))

Loss per Element:
 tensor([[1.2723, 0.0030],
        [0.7542, 1.2918],
        [0.0196, 0.6737],
        [1.3685, 2.8100]])
Mean Loss: tensor(1.0242)


In [8]:
# numpy implementation
smoothl1 = np.abs(x-y)-0.5
smoothl1[np.abs(x-y)<1] = (0.5*(x-y)**2)[np.abs(x-y)<1]

print('Loss per Element:\n', smoothl1)
print('Mean Loss:', smoothl1.mean())

Loss per Element:
 tensor([[1.2723, 0.0030],
        [0.7542, 1.2918],
        [0.0196, 0.6737],
        [1.3685, 2.8100]])
Mean Loss: tensor(1.0242)
